#!/usr/bin/env bash
# transfers file provided to specified server

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

file_path="$1"
user="$2"
key="$3"
if [ $# = 3 ]
then
    scp -i "$key" "$file_path" "$user":~/
else
    key="$4"
    scp -i "$key" "$file_path" "$user"@"$3":~/
fi