#!/usr/bin/env bash
# installs and configures a Nginx web server

if dpkg -l | grep -q "nginx";
then
    echo "installed"
else
    apt-get update
    apt-get install nginx
fi

sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html