#!/usr/bin/env bash
# configures new Ubuntu machine with Nginx server

if dpkg -l | grep -q "nginx"; then
    echo "Nginx is already installed."
else
    if ! sudo apt-get update; then
        echo "Failed to update package lists. Exiting."
        exit 1
    fi

    if ! sudo apt-get -y install nginx; then
        echo "Failed to install Nginx. Exiting."
        exit 1
    fi
fi

if ! sudo ufw allow "Nginx HTTP"; then
    echo "Failed to allow Nginx HTTP traffic in the firewall."
fi
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
service nginx start

CONFIG_FILE="/etc/nginx/sites-available/techsorce.tech"

if [ ! -f $CONFIG_FILE ];
then
    touch $CONFIG_FILE
    sudo tee "$CONFIG_FILE" > /dev/null << EOF
server {
    listen 80;
    server_name techsorce.tech;
    location /redirect_me {
        return 301 https://newdomain.com$request_uri;
    }
}
EOF
fi
