#!/usr/bin/env bash
# configures new Ubuntu machine with Nginx server
# shellcheck disable=SC2154

if dpkg -l | grep -q "nginx"; then
    echo "Nginx is already installed."
else
    if ! sudo apt-get update; then
        echo "Failed to update package lists. Exiting."
        exit 1
    fi

    if ! sudo apt-get -y install nginx; then
        echo "Failed to install Nginx. Exiting."
        exit 1
    fi
fi

if ! sudo ufw allow "Nginx HTTP"; then
    echo "Failed to allow Nginx HTTP traffic in the firewall."
fi

root_dir="/var/www/html"
echo "Hello World!" | sudo tee /"$root_dir"/index.html > /dev/null

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bk
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/pius-aaron04 permanent; ' /etc/nginx/sites-available/default
service nginx restart