#!/usr/bin/env bash
# Installs and configures HAproxy sever
# with two webs ervers uses roundrobin for load balancing among both servers

#Installation
if ! dpkg -l | grep -q "haproxy";
then
    if ! apt-get update;
    then
	printf "Failed to Update package list\nExit. . ."
        exit 1;
    fi
    if ! apt-get install haproxy -y;
    then
        printf "Failed to install HAproxy\nExiting . . ."
	exit 1
    fi
fi

# Configuration

if ! [ -e /etc/haproxy/haproxy.cfg.original ];
then
	echo "Backing up original configuration file"
	sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
else
	sudo cp /etc/haproxy/haproxy.cfg.original /etc/haproxy/haproxy.cfg
fi

if [ -e /etc/haproxy/haproxy.cfg ];
then
	sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
frontend front
	bind *:80
	default_backend back

backend back
	balance roundrobin
	server 425669-web-01 18.234.253.75:80 check
	server 425669-web-02 54.174.123.116:80 check
EOF
sudo service haproxy restart
echo "Configuration Done!"
fi
