#!/usr/bin/env bash
# Tells a story of passwd

while IFS=':' read -r USERNAME PASSWORD USID GID USERINFO HOMEDIR COMMANDSHELL
do
	echo "The user $USERNAME is part of the $GID gang, lives in $HOMEDIR and rides $COMMANDSHELL. $USID's place is protected by the passcode $PASSWORD, more info about the user here: $USERINFO"
done < /etc/passwd
