#!/usr/bin/env bash
# Prints a 7 "Best School", bad luck and good luck

var=0

while [ $var -lt 10 ]
do
	if [ $var -eq 3 ]
	then
		echo "bad luck"
	elif [ $var -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((var += 1))
done
