#!/usr/bin/env bash
# Prints information about school file

file_name=school
if [ ! -e "$file_name" ]
then
	echo "$file_name file does not exist"
	exit
else
	echo "$file_name file exists"
fi

if [ -s "$file_name" ]
then
	echo "$file_name file is not empty"
else
	echo "$file_name file is empty"
fi

if [ -f "$file_name" ]
then
	echo "$file_name is a regular file"
fi
